### ISSUE TITLE
The default config file does not work for docker

### ISSUE THREAD

**Issue by sunshineo** [pipeviz/webapp#2]
Because it is localhost
https://github.com/pipeviz/webapp/blob/master/src/config.js

Why can't we just parse host and config from window.location?
Or did I mis-understood how this project is supposed to be used?

![screen shot 2016-01-17 at 12 16 40 pm](https://cloud.githubusercontent.com/assets/1072766/12380159/d6285316-bd20-11e5-8c92-1af49ec389cb.png)

![localhost](https://cloud.githubusercontent.com/assets/1072766/12380163/ffa8cf90-bd20-11e5-9041-f1753efdb8d0.jpg)

**Comment by sdboyer** [comment]
Sorry for the delayed response - I need to set my watches on this repo (and the others).

Yes, we're moving (slowly) towards a separated "db backend" (pipeviz/pipeviz repo) vs "web frontend" (this repo) approach, which would allow multiple frontends - potentially with different backends or different configuration - to read off of the same backend. This repo will, sooner or later, likely become a node app.

It'll take us a bit to get there, but as that's the design goal, we're moving towards it incrementally.

**Comment by sunshineo** [comment]
Thanks for the reply!
